### ISSUE TITLE
Issue with importing a graphql file

### ISSUE THREAD

**Issue by OGNeutron** [prismagraphql/graphql-import#194]
`# import User from "./prisma.graphql" `

But I am getting a no directory or file error, even though they are right next to each-other:

prisma.graphql
schema.graphql

So the relatively path is correct, but graphql-import seems unable to read it.

**Comment by karloluis** [comment]
I am having the same issue where no file, no matter the path, is not being found.

**Comment by marktani** [comment]
@karloluis can you make a specific example with the working path, the non-working path, and the folder structure?

**Comment by linonetwo** [comment]
I think current the path should be relative to where you execute nodeJS.

**Comment by OGNeutron** [comment]
It was probably a rather esoteric bug, because I rebuilt it from scratch, and the problem seems to be gone,  though to respond, I did use the full path and with the new setup it worked, so as I said, must've been a rather odd bug.

**Comment by marktani** [comment]
Ok, thanks for reporting back!

Please create a new issue if you encounter a similar problem again.

**Comment by karloluis** [comment]
Using relative path like this `./schema.graphql` did not work. I used a complete path and was able to have it run. `resolve(__dirname, './schema.graphql')`
